# Generated by Django 3.0.4 on 2020-03-11 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(default=None, max_length=20)),
                ('email', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=20)),
                ('phone', models.IntegerField(max_length=13)),
                ('hit', models.IntegerField(default=0)),
                ('max_hit', models.IntegerField(default=5)),
                ('key', models.CharField(max_length=50)),
            ],
        ),
    ]
